### ISSUE TITLE
Stuck on "Other clients are in the process of synchronization, please try later"

### ISSUE THREAD

**Issue by jamesfreeman959** [Alt-er/obsidian-sync-share-server#2]
Hi there

First off, thank you for creating this amazing plugin for Obsidian - I am finding it so helpful.

Unfortunately I have a problem - I had a failed sync on one of my clients. How whenever any client tries to sync, I get the error, "Other clients are in the process of synchronization, please try later". I've tried restarting the sync server but the issue persists.

I presume that there is a lock leftover from the failed sync that needs clearing, but I don't know how to do this. Can you help please?

Also is there any way to see which client is syncing at the moment?

Thank you!

James

**Comment by Alt-er** [comment]
Delete files: `/app/user_store/{username}/sync_lock` can be unlocked manually.
The above is the path for docker deployment. If it is deployed manually, please search for the file in the directory you specified manually.

**Comment by Alt-er** [comment]
If the problem occurs again after unlocking, it means there is a problem in your synchronization process. A common situation is that when using a reverse proxy (nginx), the uploaded file size exceeds the limit when using the default configuration. There may also be other problems, you can use `docker logs obsidian-sync-share-server` to view the error stack. If it is convenient, you can send it to me and I will analyze the specific problem.

**Comment by jamesfreeman959** [comment]
Fixed - thank you so much!
